[project]
name = "polish-retail-bonds"
version = "0.1.0"
description = "Fetch, parse, and output data about Polish retail bonds."
readme = "README.md"
authors = [
    { name = "Jakub Kuczys", email = "me@jacken.men" }
]
requires-python = ">=3.14"
dependencies = [
    "niquests>=3.15.2",
    "pypdfium2>=4.30.0",
    "xlrd>=2.0.2",
]

[project.scripts]
polish-retail-bonds = "polish_retail_bonds.__main__:main"

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.406",
    "pytest>=8.4.2",
    "ruff>=0.14.0",
]

[tool.pyright]
typeCheckingMode = "strict"
# pyright really should just have these enabled by default, especially in strict mode...
reportUnnecessaryTypeIgnoreComment = true
reportUnreachable = true
# opinionated
deprecateTypingAliases = true
reportImplicitOverride = true
# disabled rules from strict mode
reportUnknownMemberType = false
stubPath = "./stubs"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = [
    "--import-mode=importlib",
]
python_files = [
    "*_test.py",
    "*_test_utils.py",
]

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
select = [
    # pyflakes rules
    "F",
    # pycodestyle rules
    "E",
    "W",
    # import sorting
    "I",
    # pyupgrade rules
    "UP",
    # flake8-bugbear rules
    "B",
    # flake8-bandit rules
    "S",
    # builtin shadowing rules
    "A",
    # unused arguments
    "ARG",
    # refurb rules
    "FURB",
    "FURB148",  # unnecessary-enumerate (in preview)
    # flake8-simplify rules
    "SIM",
    # flake8-logging rules
    "LOG",
    # flake8-logging-format rules
    "G",
    # flake8-comprehensions rules
    "C4",
    # "boolean trap" rules
    "FBT",
    # disallow implicitly concatenated strings on a single line
    # and explicitly concatenated strings
    "ISC",
    # perflint rules
    "PERF",
    # pygrep-hooks rules
    "PGH",
    # flake8-pie rules
    "PIE",
    # flake8-return rules
    "RET",
    # collection of rules unique to Ruff
    "RUF",
    # leftover `breakpoint()`
    "T100",
    # flake8-tidy-imports rules
    "TID",
]
ignore = [
    # disable __all__ sorting
    # see https://github.com/astral-sh/ruff/issues/20952
    "RUF022",
    # `assert` is expected to be used in code (to appease type checkers)
    "S101",
]
exclude = [
    "stubs/**.py",
]
preview = true
explicit-preview-rules = true

[tool.ruff.lint.isort]
combine-as-imports = true
