name: Test
on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Run pytest
        run: uv run --frozen pytest
